/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SeriesNewRouteImport } from './routes/series/new'
import { Route as BlogsSeriesSlugPostSlugRouteImport } from './routes/blogs/$seriesSlug/$postSlug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SeriesNewRoute = SeriesNewRouteImport.update({
  id: '/series/new',
  path: '/series/new',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogsSeriesSlugPostSlugRoute = BlogsSeriesSlugPostSlugRouteImport.update({
  id: '/blogs/$seriesSlug/$postSlug',
  path: '/blogs/$seriesSlug/$postSlug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/series/new': typeof SeriesNewRoute
  '/blogs/$seriesSlug/$postSlug': typeof BlogsSeriesSlugPostSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/series/new': typeof SeriesNewRoute
  '/blogs/$seriesSlug/$postSlug': typeof BlogsSeriesSlugPostSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/series/new': typeof SeriesNewRoute
  '/blogs/$seriesSlug/$postSlug': typeof BlogsSeriesSlugPostSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/series/new' | '/blogs/$seriesSlug/$postSlug'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/series/new' | '/blogs/$seriesSlug/$postSlug'
  id: '__root__' | '/' | '/series/new' | '/blogs/$seriesSlug/$postSlug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SeriesNewRoute: typeof SeriesNewRoute
  BlogsSeriesSlugPostSlugRoute: typeof BlogsSeriesSlugPostSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/series/new': {
      id: '/series/new'
      path: '/series/new'
      fullPath: '/series/new'
      preLoaderRoute: typeof SeriesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blogs/$seriesSlug/$postSlug': {
      id: '/blogs/$seriesSlug/$postSlug'
      path: '/blogs/$seriesSlug/$postSlug'
      fullPath: '/blogs/$seriesSlug/$postSlug'
      preLoaderRoute: typeof BlogsSeriesSlugPostSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SeriesNewRoute: SeriesNewRoute,
  BlogsSeriesSlugPostSlugRoute: BlogsSeriesSlugPostSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
