/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PoemsIndexRouteImport } from './routes/poems/index'
import { Route as NotesIndexRouteImport } from './routes/notes/index'
import { Route as BlogsIndexRouteImport } from './routes/blogs/index'
import { Route as SeriesNewRouteImport } from './routes/series/new'
import { Route as PoemsNewRouteImport } from './routes/poems/new'
import { Route as BlogsSeriesSlugIndexRouteImport } from './routes/blogs/$seriesSlug/index'
import { Route as BlogsSeriesSlugNewRouteImport } from './routes/blogs/$seriesSlug/new'
import { Route as BlogsSeriesSlugPostSlugRouteImport } from './routes/blogs/$seriesSlug/$postSlug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PoemsIndexRoute = PoemsIndexRouteImport.update({
  id: '/poems/',
  path: '/poems/',
  getParentRoute: () => rootRouteImport,
} as any)
const NotesIndexRoute = NotesIndexRouteImport.update({
  id: '/notes/',
  path: '/notes/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogsIndexRoute = BlogsIndexRouteImport.update({
  id: '/blogs/',
  path: '/blogs/',
  getParentRoute: () => rootRouteImport,
} as any)
const SeriesNewRoute = SeriesNewRouteImport.update({
  id: '/series/new',
  path: '/series/new',
  getParentRoute: () => rootRouteImport,
} as any)
const PoemsNewRoute = PoemsNewRouteImport.update({
  id: '/poems/new',
  path: '/poems/new',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogsSeriesSlugIndexRoute = BlogsSeriesSlugIndexRouteImport.update({
  id: '/blogs/$seriesSlug/',
  path: '/blogs/$seriesSlug/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogsSeriesSlugNewRoute = BlogsSeriesSlugNewRouteImport.update({
  id: '/blogs/$seriesSlug/new',
  path: '/blogs/$seriesSlug/new',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogsSeriesSlugPostSlugRoute = BlogsSeriesSlugPostSlugRouteImport.update({
  id: '/blogs/$seriesSlug/$postSlug',
  path: '/blogs/$seriesSlug/$postSlug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/poems/new': typeof PoemsNewRoute
  '/series/new': typeof SeriesNewRoute
  '/blogs/': typeof BlogsIndexRoute
  '/notes/': typeof NotesIndexRoute
  '/poems/': typeof PoemsIndexRoute
  '/blogs/$seriesSlug/$postSlug': typeof BlogsSeriesSlugPostSlugRoute
  '/blogs/$seriesSlug/new': typeof BlogsSeriesSlugNewRoute
  '/blogs/$seriesSlug/': typeof BlogsSeriesSlugIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/poems/new': typeof PoemsNewRoute
  '/series/new': typeof SeriesNewRoute
  '/blogs': typeof BlogsIndexRoute
  '/notes': typeof NotesIndexRoute
  '/poems': typeof PoemsIndexRoute
  '/blogs/$seriesSlug/$postSlug': typeof BlogsSeriesSlugPostSlugRoute
  '/blogs/$seriesSlug/new': typeof BlogsSeriesSlugNewRoute
  '/blogs/$seriesSlug': typeof BlogsSeriesSlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/poems/new': typeof PoemsNewRoute
  '/series/new': typeof SeriesNewRoute
  '/blogs/': typeof BlogsIndexRoute
  '/notes/': typeof NotesIndexRoute
  '/poems/': typeof PoemsIndexRoute
  '/blogs/$seriesSlug/$postSlug': typeof BlogsSeriesSlugPostSlugRoute
  '/blogs/$seriesSlug/new': typeof BlogsSeriesSlugNewRoute
  '/blogs/$seriesSlug/': typeof BlogsSeriesSlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/poems/new'
    | '/series/new'
    | '/blogs/'
    | '/notes/'
    | '/poems/'
    | '/blogs/$seriesSlug/$postSlug'
    | '/blogs/$seriesSlug/new'
    | '/blogs/$seriesSlug/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/poems/new'
    | '/series/new'
    | '/blogs'
    | '/notes'
    | '/poems'
    | '/blogs/$seriesSlug/$postSlug'
    | '/blogs/$seriesSlug/new'
    | '/blogs/$seriesSlug'
  id:
    | '__root__'
    | '/'
    | '/poems/new'
    | '/series/new'
    | '/blogs/'
    | '/notes/'
    | '/poems/'
    | '/blogs/$seriesSlug/$postSlug'
    | '/blogs/$seriesSlug/new'
    | '/blogs/$seriesSlug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PoemsNewRoute: typeof PoemsNewRoute
  SeriesNewRoute: typeof SeriesNewRoute
  BlogsIndexRoute: typeof BlogsIndexRoute
  NotesIndexRoute: typeof NotesIndexRoute
  PoemsIndexRoute: typeof PoemsIndexRoute
  BlogsSeriesSlugPostSlugRoute: typeof BlogsSeriesSlugPostSlugRoute
  BlogsSeriesSlugNewRoute: typeof BlogsSeriesSlugNewRoute
  BlogsSeriesSlugIndexRoute: typeof BlogsSeriesSlugIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/poems/': {
      id: '/poems/'
      path: '/poems'
      fullPath: '/poems/'
      preLoaderRoute: typeof PoemsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notes/': {
      id: '/notes/'
      path: '/notes'
      fullPath: '/notes/'
      preLoaderRoute: typeof NotesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blogs/': {
      id: '/blogs/'
      path: '/blogs'
      fullPath: '/blogs/'
      preLoaderRoute: typeof BlogsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/series/new': {
      id: '/series/new'
      path: '/series/new'
      fullPath: '/series/new'
      preLoaderRoute: typeof SeriesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/poems/new': {
      id: '/poems/new'
      path: '/poems/new'
      fullPath: '/poems/new'
      preLoaderRoute: typeof PoemsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blogs/$seriesSlug/': {
      id: '/blogs/$seriesSlug/'
      path: '/blogs/$seriesSlug'
      fullPath: '/blogs/$seriesSlug/'
      preLoaderRoute: typeof BlogsSeriesSlugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blogs/$seriesSlug/new': {
      id: '/blogs/$seriesSlug/new'
      path: '/blogs/$seriesSlug/new'
      fullPath: '/blogs/$seriesSlug/new'
      preLoaderRoute: typeof BlogsSeriesSlugNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blogs/$seriesSlug/$postSlug': {
      id: '/blogs/$seriesSlug/$postSlug'
      path: '/blogs/$seriesSlug/$postSlug'
      fullPath: '/blogs/$seriesSlug/$postSlug'
      preLoaderRoute: typeof BlogsSeriesSlugPostSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PoemsNewRoute: PoemsNewRoute,
  SeriesNewRoute: SeriesNewRoute,
  BlogsIndexRoute: BlogsIndexRoute,
  NotesIndexRoute: NotesIndexRoute,
  PoemsIndexRoute: PoemsIndexRoute,
  BlogsSeriesSlugPostSlugRoute: BlogsSeriesSlugPostSlugRoute,
  BlogsSeriesSlugNewRoute: BlogsSeriesSlugNewRoute,
  BlogsSeriesSlugIndexRoute: BlogsSeriesSlugIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
